import { useState, type ComponentType } from "react";
import { useTranslation } from "react-i18next";
import {
  Activity,
  Anchor,
  Antenna,
  Apple,
  Archive,
  ArchiveRestore,
  Asterisk,
  Atom,
  AtSign,
  Award,
  Axe,
  Baby,
  BadgeCheck,
  Banknote,
  Barcode,
  Battery,
  Bed,
  Beer,
  Bell,
  BellRing,
  Bike,
  Binary,
  Bird,
  Blocks,
  Bolt,
  Bone,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Braces,
  Brackets,
  Brain,
  Briefcase,
  Brush,
  Bug,
  BugPlay,
  Building,
  Building2,
  Cable,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Carrot,
  Cat,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  Church,
  Circle,
  CircleAlert,
  CircleDot,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudSun,
  CloudUpload,
  Club,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Component,
  Contact,
  Container,
  Cpu,
  CreditCard,
  Crop,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dices,
  Disc,
  Dna,
  Dog,
  DollarSign,
  DoorOpen,
  Drill,
  Droplet,
  Dumbbell,
  Euro,
  Eye,
  EyeOff,
  Factory,
  Figma,
  File,
  FileCheck,
  FileCode,
  FilePlus,
  Files,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderGit2,
  FolderKanban,
  FolderOpen,
  Frame,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitMerge,
  GitPullRequest,
  Glasses,
  Globe,
  Hammer,
  HandCoins,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Hospital,
  Hotel,
  Hourglass,
  House,
  Image,
  Images,
  Key,
  Keyboard,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Library,
  Lightbulb,
  Link,
  Link2,
  Lock,
  LockKeyhole,
  Mail,
  MailOpen,
  Map,
  MapPin,
  MapPinned,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  Moon,
  Mountain,
  Mouse,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Octagon,
  OctagonAlert,
  Package,
  PackageOpen,
  Paintbrush,
  PaintBucket,
  Palette,
  Paperclip,
  PartyPopper,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  Pickaxe,
  PiggyBank,
  Pill,
  Pin,
  Pipette,
  Pizza,
  Plane,
  Plug,
  Plug2,
  Popcorn,
  Presentation,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Radar,
  Radio,
  Receipt,
  Recycle,
  Regex,
  Rocket,
  Route,
  Router,
  Rss,
  Ruler,
  Satellite,
  SatelliteDish,
  Scale,
  ScanFace,
  ScanLine,
  School,
  Scissors,
  Send,
  Server,
  ServerCog,
  Settings,
  Settings2,
  Shapes,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  Signal,
  Signature,
  Smartphone,
  Snowflake,
  Sofa,
  Spade,
  Sparkles,
  Speaker,
  Sprout,
  Square,
  SquareTerminal,
  Stamp,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Swords,
  Syringe,
  Tablet,
  TabletSmartphone,
  Tag,
  Tags,
  Target,
  Tent,
  Terminal,
  TestTube,
  Ticket,
  Timer,
  TrafficCone,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Type,
  Umbrella,
  Unplug,
  Usb,
  User,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  Utensils,
  Video,
  Wallet,
  Wallpaper,
  Warehouse,
  Watch,
  Waves,
  Webhook,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";
import { PROJECT_COLORS, type ProjectColor, type ProjectIcon } from "@kancrm/shared";
import { cn } from "@/lib/utils";
import { filterIconGroups } from "./icon-search";

/** Bordo della card per ogni colore della palette (classi statiche: Tailwind le tiene). */
const BORDER: Record<ProjectColor, string> = {
  slate: "border-slate-400 dark:border-slate-500",
  rose: "border-rose-400 dark:border-rose-500",
  orange: "border-orange-400 dark:border-orange-500",
  amber: "border-amber-400 dark:border-amber-500",
  lime: "border-lime-500 dark:border-lime-500",
  emerald: "border-emerald-500 dark:border-emerald-500",
  teal: "border-teal-500 dark:border-teal-500",
  sky: "border-sky-400 dark:border-sky-500",
  blue: "border-blue-400 dark:border-blue-500",
  violet: "border-violet-400 dark:border-violet-500",
  fuchsia: "border-fuchsia-400 dark:border-fuchsia-500",
  stone: "border-stone-400 dark:border-stone-500",
};

/** Pastiglia di colore per il picker. */
const SWATCH: Record<ProjectColor, string> = {
  slate: "bg-slate-400",
  rose: "bg-rose-400",
  orange: "bg-orange-400",
  amber: "bg-amber-400",
  lime: "bg-lime-500",
  emerald: "bg-emerald-500",
  teal: "bg-teal-500",
  sky: "bg-sky-400",
  blue: "bg-blue-400",
  violet: "bg-violet-400",
  fuchsia: "bg-fuchsia-400",
  stone: "bg-stone-400",
};

type IconComponent = ComponentType<{ className?: string }>;

const ICONS: Record<ProjectIcon, IconComponent> = {
  Activity,
  Anchor,
  Antenna,
  Apple,
  Archive,
  ArchiveRestore,
  Asterisk,
  Atom,
  AtSign,
  Award,
  Axe,
  Baby,
  BadgeCheck,
  Banknote,
  Barcode,
  Battery,
  Bed,
  Beer,
  Bell,
  BellRing,
  Bike,
  Binary,
  Bird,
  Blocks,
  Bolt,
  Bone,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Braces,
  Brackets,
  Brain,
  Briefcase,
  Brush,
  Bug,
  BugPlay,
  Building,
  Building2,
  Cable,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Carrot,
  Cat,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  Church,
  Circle,
  CircleAlert,
  CircleDot,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudSun,
  CloudUpload,
  Club,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Component,
  Contact,
  Container,
  Cpu,
  CreditCard,
  Crop,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dices,
  Disc,
  Dna,
  Dog,
  DollarSign,
  DoorOpen,
  Drill,
  Droplet,
  Dumbbell,
  Euro,
  Eye,
  EyeOff,
  Factory,
  Figma,
  File,
  FileCheck,
  FileCode,
  FilePlus,
  Files,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderGit2,
  FolderKanban,
  FolderOpen,
  Frame,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitMerge,
  GitPullRequest,
  Glasses,
  Globe,
  Hammer,
  HandCoins,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Hospital,
  Hotel,
  Hourglass,
  House,
  Image,
  Images,
  Key,
  Keyboard,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Library,
  Lightbulb,
  Link,
  Link2,
  Lock,
  LockKeyhole,
  Mail,
  MailOpen,
  Map,
  MapPin,
  MapPinned,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  Moon,
  Mountain,
  Mouse,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Octagon,
  OctagonAlert,
  Package,
  PackageOpen,
  Paintbrush,
  PaintBucket,
  Palette,
  Paperclip,
  PartyPopper,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  Pickaxe,
  PiggyBank,
  Pill,
  Pin,
  Pipette,
  Pizza,
  Plane,
  Plug,
  Plug2,
  Popcorn,
  Presentation,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Radar,
  Radio,
  Receipt,
  Recycle,
  Regex,
  Rocket,
  Route,
  Router,
  Rss,
  Ruler,
  Satellite,
  SatelliteDish,
  Scale,
  ScanFace,
  ScanLine,
  School,
  Scissors,
  Send,
  Server,
  ServerCog,
  Settings,
  Settings2,
  Shapes,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  Signal,
  Signature,
  Smartphone,
  Snowflake,
  Sofa,
  Spade,
  Sparkles,
  Speaker,
  Sprout,
  Square,
  SquareTerminal,
  Stamp,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Swords,
  Syringe,
  Tablet,
  TabletSmartphone,
  Tag,
  Tags,
  Target,
  Tent,
  Terminal,
  TestTube,
  Ticket,
  Timer,
  TrafficCone,
  Trash2,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Type,
  Umbrella,
  Unplug,
  Usb,
  User,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  Utensils,
  Video,
  Wallet,
  Wallpaper,
  Warehouse,
  Watch,
  Waves,
  Webhook,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Zap,
};

/** Classe del bordo colorato, o null se il progetto non ha colore. */
export function projectBorderClass(color: string | null | undefined): string | null {
  return color && color in BORDER ? BORDER[color as ProjectColor] : null;
}

/** Icona del progetto (fallback: FolderKanban), come componente lucide. */
export function ProjectGlyph({
  icon,
  className,
}: {
  icon: string | null | undefined;
  className?: string;
}) {
  const Icon = (icon && ICONS[icon as ProjectIcon]) || FolderKanban;
  return <Icon className={className} />;
}

/** Riga di pastiglie colore. `null` = nessun colore (bordo grigio). */
export function ColorPicker({
  value,
  onChange,
}: {
  value: ProjectColor | null;
  onChange: (color: ProjectColor | null) => void;
}) {
  const { t } = useTranslation();
  return (
    <div className="flex flex-wrap gap-1.5">
      <button
        type="button"
        title={t("Nessun colore")}
        onClick={() => onChange(null)}
        className={cn(
          "size-6 rounded-full border border-dashed",
          value === null && "ring-2 ring-ring ring-offset-1 ring-offset-background",
        )}
      />
      {PROJECT_COLORS.map((color) => (
        <button
          key={color}
          type="button"
          title={color}
          onClick={() => onChange(color)}
          className={cn(
            "size-6 rounded-full",
            SWATCH[color],
            value === color && "ring-2 ring-ring ring-offset-1 ring-offset-background",
          )}
        />
      ))}
    </div>
  );
}

/** Griglia di icone con ricerca. `null` = icona di default. */
export function IconPicker({
  value,
  onChange,
}: {
  value: ProjectIcon | null;
  onChange: (icon: ProjectIcon | null) => void;
}) {
  const { t } = useTranslation();
  const [query, setQuery] = useState("");
  const groups = filterIconGroups(query);
  const found = groups.reduce((sum, group) => sum + group.icons.length, 0);
  return (
    <div className="flex flex-col gap-2">
      <input
        type="text"
        placeholder={t("Cerca icona…")}
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        className="h-8 rounded-md border bg-background px-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      />
      <div className="flex max-h-56 flex-col gap-2 overflow-y-auto rounded-md border p-1.5">
        {groups.map((group) => (
          <div key={group.label} className="flex flex-col gap-1">
            <p className="px-0.5 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
              {t(group.label)}
            </p>
            <div className="grid grid-cols-8 gap-1">
              {group.icons.map((name) => {
                const Icon = ICONS[name];
                const selected = value === name;
                return (
                  <button
                    key={name}
                    type="button"
                    title={name}
                    onClick={() => onChange(selected ? null : name)}
                    className={cn(
                      "flex aspect-square items-center justify-center rounded-md hover:bg-muted",
                      selected && "bg-primary text-primary-foreground hover:bg-primary",
                    )}
                  >
                    <Icon className="size-4" />
                  </button>
                );
              })}
            </div>
          </div>
        ))}
        {found === 0 && (
          <p className="py-2 text-center text-xs text-muted-foreground">
            {t("Nessuna icona per «{{query}}». Prova con un tema: sviluppo, dati, sicurezza…", {
              query: query.trim(),
            })}
          </p>
        )}
      </div>
    </div>
  );
}
